name: Deploy Laravel to Hpanel

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Hpanel

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/u128493830/domains/pintarin.id
            git clone https://github.com/ahmakbardev/pintarin_dosen.git
            cd /home/u128493830/domains/pintarin.id/pintarin_dosen
            git add .
            git commit -m "stash"
            git stash
            git pull
            chmod +x ~/bin/composer
            echo "export PATH=$HOME/bin:$PATH" >> ~/.bash_profile
            source ~/.bash_profile
            which composer
            composer --version
            composer install
            composer update
            php artisan key:generate
            php artisan route:clear
            php artisan config:cache
            php artisan optimize
            rm -rf /home/u128493830/domains/pintarin.id/public_html/dosen/*
            ln -s /home/u128493830/domains/pintarin.id/pintarin_dosen/public/* /home/u128493830/domains/pintarin.id/public_html/dosen
